# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Garage of Scv's Dream 
email: choipyo916@kaist.ac.kr
description: > # this means to ignore newlines until "baseurl:"
  Scvs_dream
baseurl: "" # the subpath of your site, e.g. /blog
url: "scvdream.github.io" # the base hostname & protocol for your site
twitter_username: none
github_username:  scvsdream

collections:
 games:
  output: true
 class:
  output: true

# Build settings
markdown: kramdown
